[package]
name = "dna"
version = "0.1.0"
authors = ["Ken Youens-Clark <kyclark@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
